### ISSUE TITLE
Globals configuration

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1025]
- [x] Release [steal@1.2.0](https://github.com/stealjs/steal/milestone/25)
- [ ] Update [steal-npm globals test](https://github.com/stealjs/steal-npm/pull/224)
- [ ] Update [steal-tools gobals test](https://github.com/stealjs/steal-tools/pull/596)
- [x] Publish [steal docs](https://github.com/stealjs/steal/pull/1036)
