### ISSUE TITLE
Remove automatic main loading

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1400]
@matthewp commented on [Wed Dec 07 2016](https://github.com/stealjs/rfcs/issues/7)

__tldr__; Remove automatic loading of a project's *main* module, and instead require the user to explicitly specify the main.

> This was discussed on a [recent live stream (39:34)](https://youtu.be/ieZJrPwSZYQ?t=39m34s) and at a [contributors meeting (1:08:10)](https://youtu.be/95OX6-qii24?t=1h8m10s)

# The Problem

Because Steal automatically loads a main (usually the package.json "main") it leads to confusion and forces developers to understand Steal internals that shouldn't be needed.

This stems from the different ways developers typically use Steal.  I see 3 primary uses:

## Application's index.html

In the application's main HTML file you will add a line like:

```html
<script src="node_modules/steal/steal.js"></script>
```

## test.html

In any test page the dev will need to add something like:

```html
<script src="node_modules/steal/steal.js" main="components/foo/foo_test"></script>
```

## demo.html

In any demo pages the developer will usually add something like:

```html
<script src="node_modules/steal/steal.js" main="@empty">
  import foo from 'foo';

  foo.bar();
</script>
```

So with the 3 primary cases, one of them you do not need to add a main, one of them you do need to add a main, and the last you do need to add a main which is really just a way to do a noop.

Given that the latter 2 cases account for the majority of the times you actually use Steal, it seems deeply wrong to me that Steal optimizes for the first, less common case, in order to make that case smaller.

Removing the automatic loading of the main would mean that users *always* need to use the main if they want to automatically load something, otherwise it will only load the configuration, so the demo case doesn't require the knowledge of the `@empty` noop.

# The Solution

Require that the `main` be specified, either in the steal script tag or in a `type=steal-module` script tag. 

Also allow for a special `~` module specifier that loads the root package's main. So instead of writing:

```js
<script src="node_modules/steal/steal.js"></script>
```

You would write:

```js
<script src="node_modules/steal/steal.js" main="~"></script>
```

Which *might* look worse to you, but consider that in demo pages instead of being:

```html
<script src="node_modules/steal/steal.js" main="@empty"></script>
<script type="steal-module">
  import foo from 'foo';

  foo.bar();
</script>
```

it is more simply:

```html
<script src="node_modules/steal/steal.js"></script>
<script type="steal-module">
  import foo from 'foo';

  foo.bar();
</script>
```

# Tasks

* [ ] - Remove automatic loading of the main in steal.js.
* [ ] - Provide a flag so that the main *can* be automatically loaded. This is mostly needed for the generated *steal.production.js* when you build.
* [ ] - Make sure using `~` as a module specifier works.
* [ ] - Update all of the documentation so that the main is shown.

# Risks

This could be annoying to some people, so we need to teach the benefits.

Additionally this would require a semver major version bump, so we should only do this if there are other semver changes that people would be willing to upgrade for.

---

@justinbmeyer commented on [Tue Aug 15 2017](https://github.com/stealjs/rfcs/issues/7#issuecomment-322494809)

> deeply wrong

It optimizes for the case a typical developer encounters first ... loading their main module.  Though I still think it makes `@empty` confusing.  

Could we make it easy for people to load the main module listed in `package.json` then?  Something like: `<script src="steal.js" main="~">`

---

@matthewp commented on [Tue Aug 15 2017](https://github.com/stealjs/rfcs/issues/7#issuecomment-322592295)

Having `~` as an alias for the packageName sounds reasonable to me.

I would probably get rid of the `main` attribute in the steal script tag altogether and instead add that to the `steal-module` scripts. It might work like:

```html
<script src="./node_modules/steal/steal.js"></script>
<script type="steal-module" name="~"></script>
```

The reason is that the `steal-module` type already is used to run demo code that expects the config to be loaded such as:

```html
<script type="steal-module">
  import can from "can";
  ...
</script>
```

I think this is better because:

1. You can add more than 1 `<script type="steal-module">` to the page to load multiple entry point modules.
2. This is parallel to how you can use `<script type="module">` (except that steal-module takes a `name` attribute rather than a `src`, could maybe support both).

**Comment by matthewp** [comment]
We're not getting rid of the `main`, just making it default to `@empty`.

**Comment by m-mujica** [comment]
on a second thought, I'm confused about why `main="~"` should work; `~` is the default for `homeAlias`, if we make steal load main when passed `~` aren't we changing the semantics of it?

```html
<script src="./node_modules/steal/steal.js" main="~"></script>
```

^ this doesn't work with steal@1.x, it tries to load `~.js`.

**Comment by matthewp** [comment]
Currently only `~/foo` works.

**Comment by m-mujica** [comment]
@matthewp what about this use case?

https://github.com/stealjs/steal/blob/7584d93fffbeca73a921264d7d8120d9af9ec25d/test/multi-main/dev.html#L12-L17

should it continue working like in that test, or are we going to ask user to provide a comma separated list of mains? :|

**Comment by m-mujica** [comment]
@matthewp that code is the test for multi main apps. I don't think there is a way to provide the list of mains using the script tag, right? 

So, I guess that we should make it work if main is an array, either in the global object or from the config file.

**Comment by matthewp** [comment]
This scenario sounds like there is no main module for the page. Otherwise the main module could import grid and slider. For this scenario I think the `steal-import` idea would be more elegant:

```js
<script src="path/to/steal.js"></script>
<steal-import from="grid"></steal-import>
<steal-import from="slider"></steal-import>
```

Or with existing tech, even this isn't too bad:

```js
<script src="path/to/steal.js">
  import "grid";
  import "slider";
</script>
```

**Comment by justinbmeyer** [comment]
@matthewp Yes, there is no main module.  I think it's slightly easier for people to `JSON.stringify()` their mains than have to transform it into JS.  But it's probably not a big difference.

**Comment by m-mujica** [comment]
@matthewp about the production workflow with this branch:

a) `<script src="./dist/steal.production.js"></script>`
The app doesn't load, even though we know what main is, since it's not coming from the script tag, steal refuses to load main.

I think the solution for this one is to make [steal-tools](https://github.com/stealjs/steal-tools/blob/cfc9cb80fc82a9bdf204aa651e7acea818b80046/lib/stream/steal.js#L49-L54) add the flag (same as main and other config props are added for the build), agreed? I called it `autoMain` but I'm not happy about it, should we change it?

When using the steal file  in `node_modules`

b)  `<script src="./node_modules/steal/steal.js" env="production" main></script>` 
The development assets are loaded instead of the built files. The reason being, `main` is undefined when [addProductionBundles](https://github.com/stealjs/steal/blob/7584d93fffbeca73a921264d7d8120d9af9ec25d/src/config.js#L132) is called. In dev mode we rely on the npm extension to set `main` for us, but that's not going to happen in production unless `addProductionBundles` does its thing.

My bet is that we should require the user to provide the main as a string, but that kinda stinks since in dev it works, **thoughts?**

c) `<script src="./node_modules/steal/steal.js" env="production" main="~/index"></script>` 
This doesn't work and I think it's just a bug on its own, **it should work right?**
![screen shot 2018-05-22 at 12 36 40 pm](https://user-images.githubusercontent.com/724877/40382961-e0d6a742-5dbc-11e8-8ccb-c0ea7cd65a22.png)

e) should we warn users when they forget to add a `main` to the script tag now? or should it be an actual error? currently it doesn't warn or throw.

**Comment by matthewp** [comment]
a) You can change it if you like, but I don't want to document `autoMain` so I don't think it matters what it is called.`loadMainOnStartup` is more technically correct maybe?

b) This is the same as always, if the main is not set (either by the script tag or by the `steal.production.js` that steal-tools creates) then steal won't know where/how to load the production bundles.

c) This likely never worked, and can't since we don't know what the name of the main bundle is.`main="package/main"` should work though.

d) main is not required, what is required is either a main in the script tag or an autoMain flag (and a main config somewhere by, something, doesn't matter where). So I think the warnings should remain the same.

**Comment by matthewp** [comment]
This is in 2.0 pre. There are a couple of docs issues to do: https://github.com/stealjs/steal/issues/1424 and https://github.com/stealjs/steal/issues/1423. Closing this though.
