### ISSUE TITLE
Steal 1.0

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#865]

**Comment by matthewp** [comment]
# Breaking Changes

* [ ] - steal-tools `bundlesPath` replaced by `dest`: https://github.com/stealjs/steal-tools/issues/491

**Comment by matthewp** [comment]
Things to do before release (incomplete):

- [ ] Update the changelog with *all* breaking changes.
- [ ] Release 1.0 of subprojects
  - [ ] - transpile
  - [ ] - steal-css
  - [ ] - steal-less
  - [ ] - steal-npm
  - [ ] - steal
  - [ ] - steal-tools
  - [ ] - grunt-steal

**Comment by matthewp** [comment]
Released!
